import os

envvars:
    "ACCESS_TOKEN",
    "RESULT_BUCKET",
    "OUTPUT_DIR",
    "TMP_DIR",
    "USER_ID",
    "INBOX_HOST",
    "DOWNLOAD_HOST",
    "WORKFLOW_ID" 

storage inbox:
    provider="s3",
    endpoint_url=os.environ["INBOX_HOST"],
    access_key=os.environ["USER_ID"],
    secret_key=os.environ["USER_ID"],
    token=os.environ["ACCESS_TOKEN"],

DATASET = "dataset"
TMP_DIR = os.path.join(os.environ["TMP_DIR"], os.environ["WORKFLOW_ID"])
RESULT_URL = os.path.join("s3://", os.environ["RESULT_BUCKET"], os.environ["OUTPUT_DIR"])


rule all: 
    pass

rule lines:
    input: 
        DATASET + "/input_files/samples_phenotypes.tsv"
    output:
        TMP_DIR + "/lines.txt"
    shell:
        "wc -l {input} > {output}"

rule words:
    input: 
        DATASET + "/input_files/samples_phenotypes.tsv"
    output:
        TMP_DIR + "/words.txt"
    shell:
        "wc -w {input} > {output}"

rule merge:
    input:
        lines=TMP_DIR + "/lines.txt",
        words=TMP_DIR + "/words.txt"
    output:
        storage.inbox(RESULT_URL + "/merged.txt")
    shell:
        "cat {input.lines} {input.words} > {output}"
